FROM phusion/baseimage:0.9.19

#ENV PYTHONUNBUFFERED 1

CMD ["/sbin/my_init", "--", "bash", "-l"]

RUN apt-get update && \
    apt-get install -y python2.7-dev python-imaging build-essential g++ && \
    apt-get install -y ssh libevent-dev libcurl4-openssl-dev libglib2.0-dev && \
    apt-get install -y uuid-dev intltool libsqlite3-dev libmysqlclient-dev && \
    apt-get install -y libarchive-dev libtool libjansson-dev valac && \
    apt-get install -y libfuse-dev python-dateutil cmake re2c flex sqlite3 && \
    apt-get install -y python-pip python-simplejson libssl-dev libldap2-dev libonig-dev && \
    apt-get autoremove -y; apt-get clean; rm /var/lib/apt/lists/* -r; rm -rf /usr/share/man/*

RUN apt-get install -y git vim; \
    apt-get autoremove -y; apt-get clean; rm /var/lib/apt/lists/* -r; rm -rf /usr/share/man/*

RUN mkdir /code
WORKDIR /code
ADD ./libevhtp /code/libevhtp
RUN cmake -DEVHTP_DISABLE_SSL=ON -DEVHTP_BUILD_SHARED=OFF . && make && make install && ldconfig


