FROM xiez/seafile-deps

ENV PYTHONUNBUFFERED 1

# Set env variables used in this Dockerfile (add a unique prefix, such as DOCKYARD)
# parent path of projects source code
ENV DOCKYARD_SRC=.

# Directory in container for all project files
ENV DOCKYARD_SRVHOME=/code

WORKDIR /code

# seahub depts
ADD $DOCKYARD_SRC/seahub/requirements.txt $DOCKYARD_SRC/seahub/test-requirements.txt /code/
RUN pip install -r /code/test-requirements.txt

# libsearpc
ADD $DOCKYARD_SRC/libsearpc /code/libsearpc
RUN cd libsearpc && ./autogen.sh && ./configure && make && make install && ldconfig

# ccnet
ADD $DOCKYARD_SRC/ccnet-server /code/ccnet-server
RUN cd ccnet-server/ && git branch -M tmp && git checkout -b v6.2.2-server v6.2.2-server && \
    ./autogen.sh && ./configure --enable-ldap && make && make install && ldconfig

# seafile
ADD $DOCKYARD_SRC/seafile-server /code/seafile-server
RUN cd seafile-server/ && git branch -M tmp && git checkout -b v6.2.2-server v6.2.2-server && \
    ./autogen.sh && ./configure && make && make install && ldconfig

# seahub
ADD $DOCKYARD_SRC/seahub /code/seahub
ADD $DOCKYARD_SRC/seafile-docker/dev/setenv.sh /code/

# run service when container start
ADD $DOCKYARD_SRC/seafile-docker/dev/start-services.sh /code
CMD ["./start-services.sh"]
