FROM phusion/baseimage:0.9.19

#ENV PYTHONUNBUFFERED 1

CMD ["/sbin/my_init", "--", "bash", "-l"]

RUN apt-get update && \
    apt-get install -y python2.7-dev build-essential g++ && \
    apt-get install -y ssh libevent-dev libcurl4-openssl-dev libglib2.0-dev && \
    apt-get install -y uuid-dev intltool libsqlite3-dev libmysqlclient-dev && \
    apt-get install -y libarchive-dev libtool libjansson-dev valac && \
    apt-get install -y libfuse-dev python-dateutil cmake re2c flex sqlite3 && \
    apt-get install -y python-pip python-simplejson libssl-dev libldap2-dev libonig-dev && \
    apt-get autoremove -y; apt-get clean; rm /var/lib/apt/lists/* -r; rm -rf /usr/share/man/*

RUN apt-get update && apt-get install -y git vim; \
    apt-get autoremove -y; apt-get clean; rm /var/lib/apt/lists/* -r; rm -rf /usr/share/man/*

RUN mkdir /code
WORKDIR /code
ADD ./libevhtp /code/libevhtp
RUN cd libevhtp && cmake -DEVHTP_DISABLE_SSL=ON -DEVHTP_BUILD_SHARED=OFF . && make && make install && ldconfig

# https://github.com/docker-library/redis/blob/master/3.2/Dockerfile
# grab gosu for easy step-down from root
# https://github.com/tianon/gosu/releases
ENV GOSU_VERSION 1.10
RUN set -ex; \
        \
        fetchDeps='ca-certificates wget'; \
        apt-get update; \
        apt-get install -y --no-install-recommends $fetchDeps; \
        rm -rf /var/lib/apt/lists/*; \
        \
        dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')"; \
        wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; \
        wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc"; \
        export GNUPGHOME="$(mktemp -d)"; \
        gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4; \
        gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; \
        rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc; \
        chmod +x /usr/local/bin/gosu; \
        gosu nobody true;
